language: node_js

stages:
  - name: deploy
    if: branch = beta AND type = push AND fork = false

before_install:
  - git clone --depth=1 --branch=master https://github.com/kodeklubben/oppgaver.git ../oppgaver

cache: yarn

script:
  - yarn eslint
  - yarn test
  - yarn build:travis

#before_deploy:
#  - git config diff.renamelimit 9999 # merge.renameLimit defaults to diff.renameLimit

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN_BETA_SKAGEVANG
  skip_cleanup: true # Don't delete artifacts created during build
  keep_history: true # Disable "force push"
  local_dir: dist
  repo: kodeklubben/beta
  target_branch: gh-pages
  fqdn: beta.oppgaver.kidsakoder.no #CNAME
  on:
    branch: beta
